server:
   port: 8080

spring:
   datasource:
      url: jdbc:mysql://localhost:3306/epidemic?serverTimezone=CST&userUnicode=true&characterEncoding=utf8
      username: root
      password: root

   messages:
       basename: i18n.list


   mail:
     username: 962188045@qq.com
     password: nmqzsnfyycwkbdgc
     host: smtp.qq.com
     properties:
        mail:
         smtp:
           ssl:
            enable: true
